production:
  application: laravel-admin-base
  hostname: 192.168.1.1
  stage: production
  roles:
    - app
  deploy_path: /var/www/app_resources
  port: 22
  user: asano
  multiplexing: true
  branch: release
  repository: https://github.com/asano/laravel-admin-base
